package database

const (
	BlackName               = "black"
	ConversationName        = "conversation"
	FriendName              = "friend"
	FriendVersionName       = "friend_version"
	FriendRequestName       = "friend_request"
	GroupName               = "group"
	GroupMemberName         = "group_member"
	GroupMemberVersionName  = "group_member_version"
	GroupJoinVersionName    = "group_join_version"
	ConversationVersionName = "conversation_version"
	GroupRequestName        = "group_request"
	GroupPinnedMsgName      = "group_pinned_msg"
	GroupMuteName           = "group_mute"
	GroupBlockName          = "group_block"
	LogName                 = "log"
	ObjectName              = "s3"
	UserName                = "user"
	SeqConversationName     = "seq"
	SeqUserName             = "seq_user"
	UserGlobalBlackName     = "user_global_black_list"
	PhoneSNInfoName         = "phone_sn_info"
	SignalInvitationName    = "signal_invitation"
	SignalRecordName        = "signal_record"
	SpamReportName          = "spam_report"
	MessageReactionName     = "message_reaction"
	MsgBurnDeadlineName     = "msg_burn_deadline"
	UserOfflineRecordName   = "user_offline_record"
	UserMuteName            = "user_mute"
	UserTotpName            = "user_totp"
	UserTotpRecoveryName    = "user_totp_recovery"
	PaymentNotificationName = "payment_notification"
	WalletBackupInfoName   = "wallet_backup_info"
)
