package database

const (
	BlackName               = "black"
	ConversationName        = "conversation"
	FriendName              = "friend"
	FriendVersionName       = "friend_version"
	FriendRequestName       = "friend_request"
	GroupName               = "group"
	GroupMemberName         = "group_member"
	GroupMemberVersionName  = "group_member_version"
	GroupJoinVersionName    = "group_join_version"
	ConversationVersionName = "conversation_version"
	GroupRequestName        = "group_request"
	LogName                 = "log"
	ObjectName              = "s3"
	UserName                = "user"
	SeqConversationName     = "seq"
	SeqUserName             = "seq_user"
	UserGlobalBlackName     = "user_global_black_list"
	PhoneSNInfoName         = "phone_sn_info"
	SignalInvitationName    = "signal_invitation"
	SignalRecordName        = "signal_record"
	SpamReportName          = "spam_report"
	CryptoDeviceName             = "crypto_device"
	CryptoGroupKeyEventName      = "crypto_group_key_event"
	CryptoGroupKeyVersionName    = "crypto_group_key_version"
)
