secret: openIM123
rpcRegisterName:
  user: user
  friend: friend
  msg: msg
  push: push
  messageGateway: messageGateway
  group: group
  auth: auth
  conversation: conversation
  third: third
  captcha: captcha
  rtc: rtc
  crypto: crypto
  redPacket: redPacket
  virgilSecurity: virgilSecurity
  openMLS: openMLS
  totp: totp

imAdminUserID: [ imAdmin ]

# 2: New login kicks all existing sessions across all platforms; only one session allowed at any time
multiLogin:
  policy: 2
  maxNumOneEnd: 30

rpcMaxBodySize:
  requestMaxBodySize: 8388608
  responseMaxBodySize: 8388608
